#!/usr/bin/env bash

# Desc: open most recently viewed files in nvim with fzf

[ "$oldfiles" ] || oldfiles="/tmp/nv-oldfiles.tmp"

nvim --headless -c "call append(0, v:oldfiles)" \
	-c "write! $oldfiles" \
	-c exit 1>/dev/null 2>&1


REGEX_SEPARATE="&"
IGLOB_SEPARATE="--"
CONNECT_REGEX=".*"
[[ -v TMUX ]] && FZF_BIN=(fzf-tmux "-p85%,90%")


while read -r file
do
	[[ -e $file ]] && DIRECTORES+="${file} "
done < $oldfiles

FLAG=/tmp/$$
FILE_R="/tmp/rg$$"
FILE_F="/tmp/fzf$$"
trap "command rm -f $FLAG $FILE_F $FILE_R" EXIT SIGINT SIGTERM
INITIAL_QUERY="${*:-}"
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case --follow --hidden "
TRANSFORM_IGLOB="
setopt extended_glob
fzf_query=\${\${FZF_QUERY## ##}%% ##}
let i=len=flag=0
while [[ i -lt \${#fzf_query} ]]; do
  if [[ \${fzf_query:\$i:${#REGEX_SEPARATE}} == '${REGEX_SEPARATE}' || \${fzf_query:\$i:${#IGLOB_SEPARATE}} == '${IGLOB_SEPARATE}' ]]; then
    if [[ flag -eq 0 ]]; then
      append_str=\"\${\${\${fzf_query:\$[i-len]:\$len}## ##}%% ##}\"
      search_str+=\"\${append_str:+\${search_str:+${CONNECT_REGEX}}}\$append_str\"
    else
      for iglob_entry in \${(s/ /)\${fzf_query:\$[i-len]:\$len}}
      do
        iglob_str+=\"'--iglob=\$iglob_entry' \"
      done
    fi
    [[ \${fzf_query:\$i:${#REGEX_SEPARATE}} == '${REGEX_SEPARATE}' ]] && let flag=0,len=0,i+=${#REGEX_SEPARATE} 
    [[ \${fzf_query:\$i:${#IGLOB_SEPARATE}} == '${IGLOB_SEPARATE}' ]] && let flag=1,len=0,i+=${#IGLOB_SEPARATE}
  else
    let len++,i++
  fi
done
if [[ len -gt 0 ]]; then
  if [[ flag -eq 0 ]]; then
    append_str=\"\${\${\${fzf_query:\$[i-len]:\$len}## ##}%% ##}\"
    search_str+=\"\${append_str:+\${search_str:+${CONNECT_REGEX}}}\$append_str\"
  else
    for iglob_entry in \${(s/ /)\${fzf_query:\$[i-len]:\$len}}
    do
      iglob_str+=\"'--iglob=\$iglob_entry' \"
    done
  fi
fi
echo \"reload:sleep 0.1; $RG_PREFIX \${iglob_str} '\$search_str' ${DIRECTORES} || true\"
"
result=$(: | ${FZF_BIN[@]:-fzf} --disabled --query "$INITIAL_QUERY" +m \
  --bind "start:unbind(?)+reload:$RG_PREFIX {q} ${DIRECTORES}" \
  --bind "change:transform:$TRANSFORM_IGLOB" \
  --bind "ctrl-t:transform:[[ ! \$FZF_PROMPT =~ Rg ]] &&
  echo \"rebind(change)+change-prompt(Rg> )+disable-search+transform-query:echo \{q} > $FILE_F; cat $FILE_R\" ||
  echo \"unbind(change)+change-prompt(Fzf> )+enable-search+transform-query:echo \{q} > $FILE_R; cat $FILE_F\"" \
  --prompt 'Rg> ' \
  --delimiter : \
  --header 'CTRL-T: Switch between ripgrep/fzf' \
  --preview 'bat --style=numbers,header,changes,snip --color=always --highlight-line {2} -- {1}' \
  --preview-window 'default:right:60%:~1:+{2}+3/2:border-left' \
  --bind="alt-e:transform:touch $FLAG; echo accept-non-empty" \
  --bind 'enter:accept')

if [[ -n "$result" ]]; then
  file_path=$(echo "$result" | awk -F: '{print $1}')
  line_number=$(echo "$result" | awk -F: '{print $2}')
  [[ -e $FLAG ]] && fzf-tmux-menu $(realpath $file_path) +$line_number || ${EDITOR} $file_path +$line_number
fi
