#!/bin/env bash

exec_action() {
    if [[ ${#directories[@]} -eq 1 ]]; then
        mkdir -p "$(dirname "${directories[0]}")" &> /dev/null
        "${EDITOR}" "${directories[@]}" > /dev/tty < /dev/tty
        return 0
    fi
    trigger_key=${directories[0]}
    unset "directories[0]"

    if [[ "${trigger_key}" == "ctrl-f" ]]; then
        "$CUSTOM_HOME/scripts/fzf/find-files" "${directories[@]}"
    elif [[ "${trigger_key}" == "ctrl-g" ]]; then
        "$CUSTOM_HOME/scripts/fzf/search-string" "${directories[@]}"
    elif [[ "${trigger_key}" == "ctrl-s" ]]; then
        tmux splitw "-bh" zsh -c "${EDITOR} ${directories[1]}"
    elif [[ "${trigger_key}" == "ctrl-v" ]]; then
        tmux splitw "-bv" zsh -c "${EDITOR} ${directories[1]}"
    elif [[ "${trigger_key}" == "ctrl-o" ]]; then
        "$CUSTOM_HOME/scripts/tmux/tmux-menu" "${directories[1]}"
    else
        "${EDITOR}" "${directories[1]}"
    fi
}

main() {
    [[ -v TMUX ]] && command -v fzf-tmux &> /dev/null && fzf_bin="fzf-tmux $FZF_TMUX_OPTS"

    typeset args
    typeset flag_nopopup flag_P filter_mode

    args=$(getopt -o P -l no-popup,mode: -n "$0" -- "$@")
    eval set -- "$args"

    while true; do
        case $1 in
        -P)
            fzf_bin=
            flag_P=1
            shift
            ;;
        --no-popup)
            flag_nopopup=1
            shift
            ;;
        --mode)
            filter_mode=$2
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "arg error"
            exit 1
            ;;
        esac
    done

    ACTION_F="execute($CUSTOM_HOME/scripts/fzf/find-files ${flag_nopopup:+-P} {+})"
    ACTION_G="execute($CUSTOM_HOME/scripts/fzf/search-string ${flag_nopopup:+-P} {+})"
    opts="
    --header-first
    --header \"keybindings: C-f(find files), C-g(grep string), C-s(hsp), C-v(vsp), C-o(fzf-tmux-menu), A-e(execute editor), Enter(editor|print)\"
    --expect \"ctrl-s,ctrl-v,ctrl-o${fzf_bin:+,ctrl-f,ctrl-g}\"
    --bind=\"ctrl-f:${ACTION_F:-accept}\"
    --bind=\"ctrl-g:${ACTION_G:-accept}\"
    --bind=\"alt-e:execute(${EDITOR} {+} > /dev/tty < /dev/tty)\"
    --bind=\"ctrl-s:accept\"
    --bind=\"ctrl-v:accept\"
    --bind=\"ctrl-o:accept\"
    --bind=\"enter:accept-or-print-query\" 
    "

    readarray -t directories < <(FILTER_FZF_DEFAULT_OPTS="$opts" fzf-filter "$filter_mode" "${flag_P:+-P}" "$@")

    [[ ${#directories[@]} -gt 0 ]] && exec_action
}

main "$@"
