#!/usr/bin/env bash

help() {
    >&2 echo 'usage:

    OPTIONS:
        -f find-files 
        -s search-string
        default editor
    '
    exit
}

toml() {
    toml_path="${CUSTOM_HOME}/scripts/tools/toml"
    config_dir="${CUSTOM_MARKS_FILE:-${XDG_CONFIG_HOME:-${HOME}/.config}/custom}"
    $toml_path "$1" -f "$config_dir/directories.toml" -t "marks" "${@:2}"
}

main() {
    [[ "$*" == *" -- "* ]] && args=$(echo "$*" | sed -nr 's/^.* -- (.*)$/\1/p')
    marks_args=$(echo "$*" | sed -rn 's/^([^-]*).*/\1/p')
    list=($(toml pmarks))
    typeset -a marks
    for abbr in $marks_args; do
        for ((i = 0; i < ${#abbr}; i++)); do
            filter_query+="${abbr:$i:1} "
        done
        mark=$(printf "%s\n" "${list[@]}" | fzf \
            --filter "^${filter_query}" \
            --tiebreak "length,begin,chunk,index" |
            sed -n '1p')
        if [[ ! ${mark} ]]; then
            printf "%s is not exists\n\n" abbr
            return 1
        fi
        marks+=("$mark")
        filter_query=
        for ((i = 0; i < ${#list[@]}; ++i)); do
            if [[ "${list[$i]}" == "$mark" ]]; then
                unset "list[$i]"
                break
            fi
        done
    done

    [[ ! "${marks[*]}" ]] && marks=(home)
    ${cmd} $args -- "${marks[@]}"

}

[[ ! -e $1 || ! -x $1 ]] && exit 1

cmd=$1
shift

main "$@"
