#!/bin/env bash

[[ -v TMUX ]] && FZF_BIN=(fzf-tmux $FZF_TMUX_OPTS )
  
typeset -a DIRECTORES ARGS

ARGS=(
  "-tf"
  "--color=always"
  "--hidden"
  "--follow"
  "--max-depth=8"
  "--size=-1M"
)

for arg in "$@"
do 
  [[ ! -d $arg ]] && info "$arg not a directory" ||
    DIRECTORES+=($arg)
done

FLAG=/tmp/$$
trap "command rm -f $FLAG" EXIT SIGINT SIGTERM
result=$(fd ${ARGS[@]} ${DIRECTORES[@]:+'^'} ${DIRECTORES[@]} |
  ${FZF_BIN[@]:-fzf} --prompt 'Files> ' \
  --delimiter / --with-nth=-3,-2,-1 \
  --bind="alt-e:transform:touch $FLAG; echo accept-non-empty" \
  --bind='enter:accept')


if [[ -n "$result" ]]; then
  [[ -e $FLAG ]] && fzf-tmux-menu $(realpath $result) || ${EDITOR} $result
fi
