#!/bin/env bash

[[ -v TMUX ]] && FZF_BIN=(fzf-tmux $FZF_TMUX_OPTS )
  
typeset -a DIRECTORES ARGS TYPES
typeset -A  DIRECTORES_LIST

DIRECTORES_LIST=(
  nv "$HOME/.config/${NVIM_APPNAME:-nvim}/lua"
  zsh "$HOME/.config/zsh"
  zzd "$HOME/.config/zsh/zsh.d"
  zzt "$HOME/.config/zsh/zinit"
  lbin "$HOME/.local/bin"
  home "$HOME"
  git "$HOME/git"
  dot "$HOME/dotfiles"
)

if [[ $# -gt 0 && "$1" =~ (help|--help|-h) ]]; then
  help() {
    echo "marks: ${!DIRECTORES_LIST[*]}"
  }
  help
  exit 0
fi

while getopts "m:n:t:dflx" opt
do
  case $opt in 
    f)
      TYPES+=("-tf");;
    d)
      TYPES+=("-td");;
    l)
      TYPES+=("-tl");;
    x)
      TYPES+=("-tx");;
    m)
      max_depth=$OPTARG;;
    n)
      min_depth=$OPTARG;;
    t)
      time="$OPTARG";;
    ?)
      echo "there is unrecognized parameter."
      echo "opts: fdlxmn."
      exit 1
  esac
done
shift $[OPTIND - 1]


ARGS=(
  "${TYPES[@]:--tf}"
  "--color=always"
  "--hidden"
  "--follow"
  "--max-depth=${max_depth:-8}"
  "--min-depth=${min_depth:-1}"
  "${time:+--changed-after=${time}}"
)

for arg in "$@"
do 
  if [[ -d ${DIRECTORES_LIST[$arg]} ]]; then
    DIRECTORES+=(${DIRECTORES_LIST[$arg]})
  else
    echo "$arg not a mark"
    exit 1
  fi
done

if [[ ${#DIRECTORES} -eq 0 ]]; then
  echo "marks not empty"
  exit 1
fi

FLAG=/tmp/$$
trap "command rm -f $FLAG" EXIT SIGINT SIGTERM
result=$(fd ${ARGS[@]} ${DIRECTORES[@]:+'^'} ${DIRECTORES[@]} |
  ${FZF_BIN[@]:-fzf} --prompt 'Files> ' \
  --delimiter / --with-nth=-3,-2,-1 \
  --bind="alt-e:transform:touch $FLAG; echo accept-non-empty" \
  --bind='enter:accept')


if [[ -n "$result" ]]; then
  [[ -e $FLAG ]] && fzf-tmux-menu $(realpath $result) || ${EDITOR} $result
fi
