#!/bin/env zsh

[[ -v TMUX && $TMUX_SESSION != manpager ]] && FZF_BIN=(fzf-tmux $FZF_TMUX_OPTS )

# accessdb (8)         - 以易读的格式转储 man-db 数据库的内容
# 从上解析出 accessdb 8
result=$(
  ${FZF_BIN:-fzf} --prompt "Man> " --nth=1,2 +m | 
  sed -nr 's/^([a-z]+) \(([0-9])\).*/\1 \2/p') < <(man -k .)


[[ -n $result ]] && {
  # 传给man，将内容使用nvim的man文件类型显示。
  echo $result | xargs -o man | nvim -c 'Man!'
}

