#!/bin/env bash

# 改良（使用while 循环遍历）
# 1. 使用 -- 来声明 iglob通配符表达式,可以有多个, 可以在任意位置
# 2. 使用 & 来连接多个正则表达式，实现类似连续模糊查找的效果,可以在任意位置
# （对于单个正则，它的效果和原来相同, 内部使用.*来连接）
# （多个连续的&没有效果（符合逻辑）)
# 3. 尝试解决\b在bash和正则之间的冲突，可惜没有成功。\b 需要键入\\b,其他如常
# 4. 使用 REGEX_SEPARATE IGLOB_SEPARATE CONNECT_REGEX 变量代替字面量
# 例如 ^env & cb &cd => ^env.*cb.cd
#      -- *ab* *fd* -- a* => --iglob *ab* *fd* a*
#      -- *fd* & ^fd -- *rg*&cd => --iglob *fd* *rg*    ^fd.*cd
#
#
# 如有需要可添加：-- 可以识别 H F D[\d] ... 展开为 --hidden --follow --max-depth=\d ... 
# 例如 -- *fd* H *rg* D4 => --iglob *fd* --iglob *rg* --hidden --max-depth=4
# 只需要添加一个case即可

REGEX_SEPARATE="&"
IGLOB_SEPARATE="--"
CONNECT_REGEX=".*"
[[ -v TMUX ]] && FZF_BIN=(fzf-tmux "-p85%,90%")
  
if [[ $# > 0 && ! -e $1 ]]; then
  INITIAL_QUERY=$1
  shift
fi

for arg in "$@"
do 
  [[ ! -d $arg ]] && info "$arg not a directory" ||
    DIRECTORES+="$arg "
done

FLAG=/tmp/$$
FILE_R="/tmp/rg$$"
FILE_F="/tmp/fzf$$"
trap "command rm -f $FLAG $FILE_R $FILE_F" EXIT SIGINT SIGTERM
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case --hidden --follow"
TRANSFORM_IGLOB="
setopt extended_glob
fzf_query=\${\${FZF_QUERY## ##}%% ##}
let i=len=flag=0
while [[ i -lt \${#fzf_query} ]]; do
  if [[ \${fzf_query:\$i:${#REGEX_SEPARATE}} == '${REGEX_SEPARATE}' || \${fzf_query:\$i:${#IGLOB_SEPARATE}} == '${IGLOB_SEPARATE}' ]]; then
    if [[ flag -eq 0 ]]; then
      append_str=\"\${\${\${fzf_query:\$[i-len]:\$len}## ##}%% ##}\"
      search_str+=\"\${append_str:+\${search_str:+${CONNECT_REGEX}}}\$append_str\"
    else
      for iglob_entry in \${(s/ /)\${fzf_query:\$[i-len]:\$len}}
      do
        iglob_str+=\"'--iglob=\$iglob_entry' \"
      done
    fi
    [[ \${fzf_query:\$i:${#REGEX_SEPARATE}} == '${REGEX_SEPARATE}' ]] && let flag=0,len=0,i+=${#REGEX_SEPARATE} 
    [[ \${fzf_query:\$i:${#IGLOB_SEPARATE}} == '${IGLOB_SEPARATE}' ]] && let flag=1,len=0,i+=${#IGLOB_SEPARATE}
  else
    let len++,i++
  fi
done
if [[ len -gt 0 ]]; then
  if [[ flag -eq 0 ]]; then
    append_str=\"\${\${\${fzf_query:\$[i-len]:\$len}## ##}%% ##}\"
    search_str+=\"\${append_str:+\${search_str:+${CONNECT_REGEX}}}\$append_str\"
  else
    for iglob_entry in \${(s/ /)\${fzf_query:\$[i-len]:\$len}}
    do
      iglob_str+=\"'--iglob=\$iglob_entry' \"
    done
  fi
fi
echo \"reload:sleep 0.1; $RG_PREFIX \${iglob_str} '\$search_str' ${DIRECTORES} || true\"
"

result=$(: | ${FZF_BIN[@]:-fzf} --disabled --query "$INITIAL_QUERY" +m \
  --bind "start:unbind(?)+reload:$RG_PREFIX {q} ${DIRECTORES}" \
  --bind "change:transform:$TRANSFORM_IGLOB" \
  --bind "ctrl-t:transform:[[ ! \$FZF_PROMPT =~ Rg ]] &&
  echo \"rebind(change)+change-prompt(Rg> )+disable-search+transform-query:echo \{q} > $FILE_F; cat $FILE_R\" ||
  echo \"unbind(change)+change-prompt(Fzf> )+enable-search+transform-query:echo \{q} > $FILE_R; cat $FILE_F\"" \
  --prompt 'Rg> ' \
  --delimiter : \
  --header 'CTRL-T: Switch between ripgrep/fzf' \
  --preview 'bat --style=numbers,header,changes,snip --color=always --highlight-line {2} -- {1}' \
  --preview-window 'default:right:60%:~1:+{2}+3/2:border-left' \
  --bind="alt-e:transform:touch $FLAG; echo accept-non-empty" \
  --bind 'enter:accept')


if [[ -n "$result" ]]; then
  file_path=$(echo "$result" | awk -F: '{print $1}')
  line_number=$(echo "$result" | awk -F: '{print $2}')
  [[ -e $FLAG ]] && fzf-tmux-menu $(realpath $file_path) +$line_number || ${EDITOR} $file_path +$line_number
fi



# 两点改良（使用while 循环遍历）
# 1. 使用 -- 来声明 iglob通配符表达式,可以有多个, 可以在任意位置
# 2. 使用 & 来连接多个正则表达式，实现类似连续模糊查找的效果,可以在任意位置
# （对于单个正则，它的效果和原来相同, 内部使用.*来连接）
# （多个连续的&&没有效果（符合逻辑）)
# 3. 尝试解决\b在bash和正则之间的冲突，可惜没有成功。\b 需要键入\\b,其他如常

# TRANSFORM_IGLOB="
# setopt extended_glob
# fzf_query=\${\${FZF_QUERY## ##}%% ##}
# let i=len=flag=0
# echo '----------------------' >> ~/all.log
# while [[ i -lt \${#fzf_query} ]]; do
#   if [[ \${fzf_query:\$i:1} == '&' || \${fzf_query:\$i:2} == '--' ]]; then
#     [[ i -lt \${#fzf_query} ]] && echo char \${fzf_query:\$i:1} >> ~/all.log
#     echo entry start:\$[i-len] len:\$len \${fzf_query:\$[i-len]:\$len} >> ~/all.log
#     
#     if [[ flag -eq 0 ]]; then
#       echo '进入到search' >> ~/all.log
#       append_str=\"\${\${\${fzf_query:\$[i-len]:\$len}## ##}%% ##}\"
#       search_str+=\"\${append_str:+\${search_str:+.*}}\$append_str\"
#       echo search_str:\$search_str >> ~/all.log
#     else
#       echo '进入到iglob' >> ~/all.log
#       for iglob_entry in \${(s/ /)\${fzf_query:\$[i-len]:\$len}}
#       do
#         iglob_str+=\"'--iglob=\$iglob_entry' \"
#       done
#     fi
#     [[ \${fzf_query:\$i:1} == '&' ]] && let flag=0,len=0,i+=1 
#     [[ \${fzf_query:\$i:2} == '--' ]] && let flag=1,len=0,i+=2 
#   else
#     let len++,i++
#   fi
#   # echo i:\${i} fzf:\${#fzf_query} len:\${len} flag:\${flag} >> ~/all.log
# done
# if [[ len -gt 0 ]]; then
#   if [[ flag -eq 0 ]]; then
#     search_str+=\"\${search_str:+.*}\${\${\${fzf_query:\$[i-len]:\$len}## ##}%% ##}\"
#     echo search_str:\$search_str >> ~/all.log
#   else
#     for iglob_entry in \${(s/ /)\${fzf_query:\$[i-len]:\$len}}
#     do
#       iglob_str+=\"'--iglob=\$iglob_entry' \"
#     done
#   fi
# fi
# echo done:\$search_str >> ~/all.log
# echo done:\$iglob_str >> ~/all.log
# echo \"reload:sleep 0.1; $RG_PREFIX \${iglob_str} '\${search_str}' ${DIRECTORES} || true\"
# "


# 1. 相对于第一种，-- iglob通配符表达式不仅可以放到末尾，也可以放到开头解析。
#   如果放到开头，需要以&来声明正则表达式

# TRANSFORM_IGLOB="
# setopt extended_glob
# fzf_query=\${\${FZF_QUERY## ##}%% ##}
# if [[ \${fzf_query} =~ \"^[^ ].*--\" ]]; then
#   for iglob_entry in \${(s/ /)\${fzf_query##*--}}
#   do
#     iglob_str+=\"'--iglob=\$iglob_entry' \"
#   done
#   search_str=\"\${\${fzf_query%--*}%% ##}\"
#   echo \$iglob_str > ~/1.log
#   echo \$search_str >> ~/1.log
# elif [[ \${fzf_query} =~ \"^--\" ]]; then
#   for iglob_entry in \${(s/ /)\${\${fzf_query%%|*}#--}}
#   do
#     iglob_str+=\"'--iglob=\$iglob_entry' \"
#   done
#   [[ ! \${fzf_query} =~ \"\|\" ]] && search_str='' || 
#     search_str=\"\${\${fzf_query#*|}## ##}\"
#   echo \$iglob_str > ~/2.log
#   echo \$search_str >> ~/2.log
# else
#   search_str=\"\${fzf_query}\"
# fi
# echo \"reload:sleep 0.1; $RG_PREFIX \${iglob_str} '\${search_str}' ${DIRECTORES} || true\"
# "

# 1. 增加了在末尾使用 -- 定义 iglob通配符表达式

# TRANSFORM_IGLOB="
# if [[ \${FZF_QUERY} =~ \"[ ]?--\" ]]; then
#   setopt extended_glob
#   echo \${FZF_QUERY%--*} > ~/1.log
#   echo \${FZF_QUERY##*--} >> ~/1.log
#   for iglob_entry in \${(s/ /)\${FZF_QUERY##*--}}
#   do
#     iglob_str+=\"'--iglob=\$iglob_entry' \"
#   done
#   search_str=\"\${FZF_QUERY% ##--*}\"
#   echo \$iglob_str >> ~/iglob.log
# else
#   search_str=\"\${FZF_QUERY}\"
# fi
# echo \$search_str \$#search_str > 1.log
# echo \$iglob_str >> 1.log
# echo \$search_str >> ~/3.log
# echo {q} >> ~/2.log
# test_iglob=\"'--iglob=*fd*' '--iglob=*rg*'\"
#
# echo \"reload:sleep 0.1; $RG_PREFIX \${iglob_str} '\${search_str}' ${DIRECTORES} || true\"
# "
