#!/bin/env bash

REGEX_SEPARATE="&"
IGLOB_SEPARATE="--"
CONNECT_REGEX=".*"
typeset -A MARKS_LIST=(
    [nv]="$HOME/.config/${NVIM_APPNAME:-nvim}/lua"
    [zsh]="$HOME/.config/zsh"
    [zzd]="$HOME/.config/zsh/zsh.d"
    [zzt]="$HOME/.config/zsh/zinit"
    [lbin]="$HOME/.local/bin"
    [home]="$HOME"
    [git]="$HOME/git"
    [dot]="$HOME/dotfiles"
)

help() {
    >&2 echo 'usage: rg [OPTIONS] [DIRECTORES] [--] [DIRECTORY MARKS]

    OPTIONS:
        -x executable files
        -t changed after time ( 1min 1h 1d(default) 2weeks "2018-10-27 10:00:00" 2018-10-27)
        -D max-depth
        -h cancel --hidden
        -n --no-ignore
        -g ls git files (mdkois)
        --
        add marks ...
    '
    exit
}

parse_args() {
    typeset changed_time type max_depth=8 no_ignore hidden=true

    args=$(getopt -o xhnD:t::g:: -n "$0" -- "$@")

    if [[ $? != 0 ]]; then
        echo "getopt parse error"
        exit 1
    fi

    eval set -- "$args"

    while true
    do
        case "$1" in
            -g)
                if ! git rev-parse --is-inside-work-tree &> /dev/null; then
                    echo "not a git directory"
                    exit 1
                fi
                if [[ -n $2 ]]; then
                    flags=$2
                    let i=0
                    while [[ $i -lt ${#flags} ]]; do
                        case ${flags:$i:1} in
                            m)
                                GIT_FLAGS+=("--modified")
                                ;;
                            d)
                                GIT_FLAGS+=("--deleted")
                                ;;
                            s)
                                GIT_FLAGS+=("--stage")
                                ;;
                            k)
                                GIT_FLAGS+=("--killed")
                                ;;
                            i)
                                GIT_FLAGS+=("--ignored")
                                ;;
                            o)
                                GIT_FLAGS+=("--others")
                                ;;
                            *)
                                echo "flag error"
                                exit 1
                                ;;
                        esac
                        let i++
                    done
                fi
                GIT=true
                shift 2
                ;;
            -x)
                type="-tx"
                shift
                ;;
            -t)
                case $2 in
                    "")
                        changed_time="--changed-after=1d"
                        ;;
                    *)
                        changed_time="--changed-after=$2"
                        ;; 
                esac 
                shift 2
                ;;
            -h)
                unset hidden
                shift
                ;;
            -n)
                no_ignore=true
                shift
                ;;
            -D)
                max_depth=$2
                shift 2
                ;;
            --)
                shift
                break
                ;;
            ?)
                echo "args $1 $2 error"
                exit 1
                ;;
        esac
    done

    RG_OPTS=(
        "--column"
        "--line-number"
        "--no-heading"
        "--color=always"
        "--smart-case"
        "--follow"
    )
    if [[ -z $changed_time ]]; then
        RG_OPTS+=(
            "--max-depth=${max_depth}"
            ${hidden:+--hidden}
            ${no_ignore:+--no-ignore}
        )
    else
        FD_OPTS=(
            "--follow"
            "--max-depth=${max_depth}"
            "${type:--tf}"
            ${hidden:+--hidden}
            ${no_ignore:+--no-ignore}
            ${changed_time}
        )
    fi

    if [[ $# -gt 0 && ! -e "$1" ]]; then
        INITIAL_QUERY="$1"
        shift
    fi
    
    for arg in "$@"
    do
        if [[ ! -d $arg ]]; then
            echo "$arg is not a directory"
            exit 1
        fi
        DIRECTORES+=("$arg")
    done
}

check_mark() {
    for arg in "$@"
    do
        if [[ -d ${MARKS_LIST[$arg]} ]]; then
            DIRECTORES+=("${MARKS_LIST[$arg]}")
        else
            echo "$arg not a mark"
            exit 1
        fi
    done
}
main() {
    [[ $# -gt 0 &&  "$1" == help ]] && help
    [[ -v TMUX ]] && fzf_bin="fzf-tmux -p85%,90%"

    typeset -a FD_OPTS RG_OPTS DIRECTORES GIT_FLAGS
    typeset INITIAL_QUERY GIT

    ((g=1))
    while [[ g -le $# && "${!g}" != "--" ]]; do
        ((g++))
    done

    parse_args "${@:1:$g}"

    if [[ -n $GIT ]]; then
        DIRECTORES=($(command git ls-files "${GIT_FLAGS[@]}" "${DIRECTORES[@]}"))
    elif [[ ${#FD_OPTS[@]} -gt 0 ]];then
        DIRECTORES=($(command fd "${FD_OPTS[@]}" "${DIRECTORES[@]}"))
        check_mark "${@:$((g + 1))}"
    else
        check_mark "${@:$((g + 1))}"
    fi

    flag=/tmp/$$
    file_r="/tmp/rg$$"
    file_f="/tmp/fzf$$"
    trap "command rm -f $flag $file_r $file_f" EXIT SIGINT SIGTERM
    transform_iglob="
    setopt extended_glob
    fzf_query=\${\${FZF_QUERY## ##}%% ##}
    let i=len=flag=0
    while [[ i -lt \${#fzf_query} ]]; do
        if [[ \${fzf_query:\$i:${#REGEX_SEPARATE}} == '${REGEX_SEPARATE}' || \${fzf_query:\$i:${#IGLOB_SEPARATE}} == '${IGLOB_SEPARATE}' ]]; then
            if [[ flag -eq 0 ]]; then
              append_str=\"\${\${\${fzf_query:\$[i-len]:\$len}## ##}%% ##}\"
              search_str+=\"\${append_str:+\${search_str:+${CONNECT_REGEX}}}\$append_str\"
            else
              for iglob_entry in \${(s/ /)\${fzf_query:\$[i-len]:\$len}}
              do
                  iglob_str+=\"'--iglob=\$iglob_entry' \"
              done
            fi
            [[ \${fzf_query:\$i:${#REGEX_SEPARATE}} == '${REGEX_SEPARATE}' ]] && let flag=0,len=0,i+=${#REGEX_SEPARATE} 
            [[ \${fzf_query:\$i:${#IGLOB_SEPARATE}} == '${IGLOB_SEPARATE}' ]] && let flag=1,len=0,i+=${#IGLOB_SEPARATE}
        else
            let len++,i++
        fi
    done
    if [[ len -gt 0 ]]; then
        if [[ flag -eq 0 ]]; then
            append_str=\"\${\${\${fzf_query:\$[i-len]:\$len}## ##}%% ##}\"
            search_str+=\"\${append_str:+\${search_str:+${CONNECT_REGEX}}}\$append_str\"
        else
            for iglob_entry in \${(s/ /)\${fzf_query:\$[i-len]:\$len}}
            do
                iglob_str+=\"'--iglob=\$iglob_entry' \"
            done
        fi
    fi
    echo \"reload:sleep 0.1;rg ${RG_OPTS[*]} \${iglob_str} '\$search_str' ${DIRECTORES[*]} || true\"
    "
    
    result=$(: | ${fzf_bin:-fzf} --disabled --query "$INITIAL_QUERY" +m \
        --bind "start:unbind(?)+reload:rg ${RG_OPTS[*]} {q} ${DIRECTORES[*]}" \
        --bind "change:transform:$transform_iglob" \
        --bind "ctrl-t:transform:[[ ! \$FZF_PROMPT =~ Rg ]] &&
            echo \"rebind(change)+change-prompt(Rg> )+disable-search+transform-query:echo \{q} > $file_f; cat $file_r\" ||
            echo \"unbind(change)+change-prompt(Fzf> )+enable-search+transform-query:echo \{q} > $file_r; cat $file_f\"" \
        --prompt 'Rg> ' \
        --delimiter : \
        --header 'CTRL-T: Switch between ripgrep/fzf' \
        --preview 'bat --style=numbers,header,changes,snip --color=always --highlight-line {2} -- {1}' \
        --preview-window 'default:right:60%:~1:+{2}+3/2:border-left' \
        --bind="alt-e:transform:touch $flag; echo accept-non-empty" \
        --bind 'enter:accept')

    if [[ -n "$result" ]]; then
        file_path=$(echo "$result" | awk -F: '{print $1}')
        line_number=$(echo "$result" | awk -F: '{print $2}')
        if [[ -e $flag ]]; then
            fzf-tmux-menu $(realpath $file_path) +$line_number
        else
            ${EDITOR} $file_path +$line_number
        fi
    fi
}

main "$@"
