#!/bin/env bash

main() {
    if [[ ! -v TMUX ]]; then
        echo "tmux is not exists"
        return 1
    fi

    [[ $# -eq 0 ]] && return 1

    tmux display-menu -T "Choose direction" \
        "left" h "splitw -bh zsh -c \"cd $PWD; ${EDITOR} ${*}\"" \
        "right" r "splitw -h zsh -c \"${EDITOR} ${*}\"" \
        "top" k "splitw -bv zsh -c \"${EDITOR} ${*}\"" \
        "bottom" j "splitw -v zsh -c \"${EDITOR} ${*}\"" \
        "left full" H "splitw -fbh zsh -c \"${EDITOR} ${*}\"" \
        "right full" L "splitw -fh zsh -c \"${EDITOR} ${*}\"" \
        "top full" K "splitw -fbv zsh -c \"${EDITOR} ${*}\"" \
        "bottom full" J "splitw -fv zsh -c \"${EDITOR} ${*}\"" \
        "new window" w "neww zsh -c \"${EDITOR} ${*}\"" || return 1
}

main "$@"
