#!/bin/env bash

help() {
    >&2 echo '
    usage: command

    OPTIONS:
        -P 当前进程不在tmux弹出窗口中执行

        --no-popup 动作不在弹出窗口中执行
    '
    exit
}

filter() {
    if [[ $# -eq 0 ]]; then
        echo "cat"
    else
        echo "fzf --filter \"${*}\" --exact --scheme history --tiebreak \"end,chunk,index\""
    fi
}

zoxide_directores() {
    if [[ -z ${fzf_bin} ]]; then
        action_f="execute($CUSTOM_HOME/scripts/fzf/find-files ${flag_nopopup:+-P} {+})"
        action_g="execute($CUSTOM_HOME/scripts/fzf/search-string ${flag_nopopup:+-P} {+})"
    fi

    # shellcheck disable=SC2068
    readarray -t directories < <(
        zoxide query --list | eval "$(filter $@)" | lscolors |
            ${fzf_bin:-fzf} \
                --prompt "Zoxide> " \
                --exact --scheme history \
                --delimiter / --nth -1,-2,-3 \
                --exit-0 --header-first \
                --header "keybindings: C-f(find files), C-g(grep string), C-s(hsp), C-v(vsp), C-o(fzf-tmux-menu), A-e(execute editor), Enter(editor|print)" \
                --expect "ctrl-s,ctrl-v,ctrl-o""${fzf_bin:+,ctrl-f,ctrl-g}" \
                --bind="ctrl-f:${action_f:-accept}" \
                --bind="ctrl-g:${action_g:-accept}" \
                --bind="alt-e:execute(${EDITOR} {+} > /dev/tty < /dev/tty)" \
                --bind="ctrl-s:accept" \
                --bind="ctrl-v:accept" \
                --bind="ctrl-o:accept" \
                --bind="enter:accept-or-print-query"
    )
}

exec_action() {
    if [[ ${#directories[@]} -eq 1 ]]; then
        mkdir -p "$(dirname "${directories[0]}")" &> /dev/null
        "${EDITOR}" "${directories[@]}" > /dev/tty < /dev/tty
        return 0
    fi
    trigger_key=${directories[0]}
    unset "directories[0]"

    if [[ "${trigger_key}" == "ctrl-f" ]]; then
        "$CUSTOM_HOME/scripts/fzf/find-files" "${directories[@]}"
    elif [[ "${trigger_key}" == "ctrl-g" ]]; then
        "$CUSTOM_HOME/scripts/fzf/search-string" "${directories[@]}"
    elif [[ "${trigger_key}" == "ctrl-s" ]]; then
        tmux splitw "-bh" zsh -c "${EDITOR} ${directories[1]}"
    elif [[ "${trigger_key}" == "ctrl-v" ]]; then
        tmux splitw "-bv" zsh -c "${EDITOR} ${directories[1]}"
    elif [[ "${trigger_key}" == "ctrl-o" ]]; then
        "$CUSTOM_HOME/scripts/tmux/tmux-menu" "${directories[1]}"
    else
        "${EDITOR}" "${directories[1]}"
    fi
}

main() {
    [[ -v TMUX ]] && command -v fzf-tmux &> /dev/null && fzf_bin="fzf-tmux $FZF_TMUX_OPTS"

    typeset -a directories

    typeset args
    typeset flag_nopopup

    args=$(getopt -o P -l no-popup -n "$0" -- "$@")
    eval set -- "$args"

    while true; do
        case $1 in
        -P)
            fzf_bin=
            shift
            ;;
        --no-popup)
            flag_nopopup=1
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "arg error"
            exit 1
            ;;
        esac
    done

    zoxide_directores "$@"

    [[ ${#directories[@]} -gt 0 ]] && exec_action
}

main "$@"
