#!/usr/bin/env bash

help() {
    >&2 echo 'usage: ff [OPTIONS] [DIRECTORIES] [--] [DIRECTORY MARKS]

    OPTIONS:
        -f find-files 
        -s search-string
        default editor
    '
    exit
}

main() {
    fzf_prefix="$CUSTOM_HOME/scripts/fzf"

    while getopts "fs" opt; do
        case $opt in
        f)
            cmd=$fzf_prefix"/find-files"
            ;;
        s)
            cmd=$fzf_prefix"/search-string"
            ;;
        *)
            printf "flag %s error\n\n" OPTARG
            ;;
        esac

    done
    shift $((OPTIND - 1))

    [[ -z $parse_toml ]] && source "${CUSTOM_HOME}/scripts/tools/parse-toml"

    typeset -a marks
    for abbr in "$@"; do
        for ((i = 0; i < ${#abbr}; i++)); do
            filter_query+="${abbr:$i:1} "
        done
        mark=$(toml::pmarks | fzf \
            --filter "^${filter_query}" \
            --tiebreak "length,begin,chunk,index" |
            sed -n '1p')
        if [[ ! ${mark} ]]; then
            printf "%s is not exists\n\n" abbr
            return 1
        else
            marks+=("$mark")
        fi
    done

    [[ ! "${marks[*]}" ]] && marks=(home)
    if [[ "${cmd}" ]]; then
        ${cmd} -- "${marks[@]}"
    else
        ${EDITOR} "$(toml::gmark "${marks}")"
    fi

}

main "$@"
