#!/bin/env bash

help() {
    >&2 echo 'usage: ff [OPTIONS] [DIRECTORIES] [--] [DIRECTORY MARKS]

    OPTIONS:
        -t char set, file types dfxlspebc
        -T string, changed after time ( 1min 1h 1d(default) 2weeks "2018-10-27 10:00:00" 2018-10-27)
        -D int, max-depth
        -h bool, cancel --hidden
        -I bool, --no-ignore
        -q string, init_query

        --
        add marks ...
    KEYBINDINGS:
        ctrl-s horizontal direction splitw
        ctrl-v vertical direction splitw
        ctrl-x transform-query:echo $(dirname {})/ 
        alt-e fzf-tmux-menu splitw
    '
    exit
}

add_regular_directores() {
    for arg in "$@"; do
        if [[ -d "$arg" ]]; then
            directories+=("$arg")
        else
            echo "$arg not a directory"
            exit 1
        fi
    done

}

add_mark_directores() {
    [[ -z $parse_toml ]] && source "${CUSTOM_HOME}/scripts/tools/parse-toml"

    for arg in "$@"; do
        dirs=$(toml::gmark "$arg")
        if [[ $? -ne 0 ]]; then
            exit 1
        fi
        for dir in ${dirs}; do
            if [[ -d $dir ]]; then
                directories+=("$dir")
            else
                echo "$dir" | lscolors >> $ff_file
            fi
        done
    done
}

fzf_search() {
    action=/tmp/$$
    [[ -e $action ]] && exit 1
    trap "command rm -f $action $ff_file" EXIT SIGINT SIGTERM

    action_e="execute(${EDITOR} {+} > /dev/tty < /dev/tty)"

    if [[ -e $ff_file ]]; then
        $fd_prefix >> $ff_file
        cmd="cat ${ff_file}"
    else
        cmd="${fd_prefix}"
    fi

    readarray -t files < <(
        $cmd | ${fzf_bin:-fzf} \
            --query "$init_query" --prompt 'Files> ' \
            --scheme path --exact --tiebreak "end,chunk,index" \
            --header-first --header "keybindings:C-s(hsp), C-v(vsp), C-o(fzf-tmux-menu), A-e(execute editor), Enter(select or new file)" \
            --bind="ctrl-s:transform:echo h > $action; echo accept" \
            --bind="ctrl-v:transform:echo v > $action; echo accept" \
            --bind="ctrl-o:transform:echo m > $action; echo accept" \
            --bind="alt-e:transform:[[ \"${fzf_bin}\" ]] && echo \"ignore\" || echo \"${action_e}\"" \
            --bind="enter:accept-or-print-query"
    )
}

exec_action() {
    flag=$(command cat "$action" 2> /dev/null)

    mkdir -p "$(dirname "${files}")" &> /dev/null
    if [[ "${flag}" =~ ^(h|v)$ ]]; then
        tmux splitw "-b${flag}" zsh -c "${EDITOR} ${files[*]}"
    elif [[ "${flag}" == m ]]; then
        "$CUSTOM_HOME/scripts/tmux/tmux-menu" "$(realpath "${files[@]}")"
    else
        ${EDITOR} "${files[@]}"
    fi
}

main() {
    [[ $# -gt 0 && "$1" == help ]] && help
    [[ -v TMUX ]] && command -v fzf-tmux &> /dev/null && fzf_bin="fzf-tmux $FZF_TMUX_OPTS"

    # global
    typeset -a directories files
    typeset action fd_prefix ff_file=/tmp/ff-$$

    # args
    typeset -a types left_args right_args add_args
    typeset max_depth=8 hidden=true

    ((i = 1))
    while [[ i -le $# && "${!i}" != "--" ]]; do
        left_args+=("${!i}")
        ((i++))
    done
    right_args=("${@:$((i + 1))}")

    args=$(getopt -o hID:t:T:q:e:E: -l no-popup -n "$0" -- "${left_args[@]}")
    if [[ $? != 0 ]]; then
        echo "getopt parse error"
        exit 1
    fi
    eval set -- "$args"

    while true; do
        case "$1" in
        --no-popup)
            fzf_bin=
            shift
            ;;
        -t)
            ((i = 0))
            while [[ $i -lt ${#2} ]]; do
                ((i++))
                types+=("-t$(echo "$2" | cut -c $i)")
            done
            shift 2
            ;;
        -T)
            add_args+=("--changed-after=$2")
            shift 2
            ;;
        -h)
            unset hidden
            shift
            ;;
        -I)
            add_args+=("--no-ignore")
            shift
            ;;
        -D)
            max_depth=$2
            shift 2
            ;;
        -q)
            init_query=$2
            shift 2
            ;;
        -e)
            while read -r ext; do
                add_args+=("--extension=$ext")
            done < <(echo "$2" | tr ',' '\n')
            shift 2
            ;;
        -E)
            while read -r glob; do
                add_args+=("--exclude=$glob")
            done < <(echo "$2" | tr ',' '\n')
            shift 2
            ;;
        --)
            shift
            break
            ;;
        ?)
            echo "args error"
            exit 1
            ;;
        esac
    done

    [[ $# -gt 0 ]] && add_regular_directores "$@"
    [[ ${#right_args} -gt 0 ]] && add_mark_directores "${right_args[@]}"

    fd_prefix="command fd --color=always --follow --max-depth=${max_depth} \
        ${hidden:+--hidden} ${add_args[*]} ${types[*]--tf} \
        ${directories[*]:+^} ${directories[*]}"

    fzf_search

    [[ ${#files[@]} -gt 0 ]] && exec_action
}
main "$@"
