#!/bin/env bash

help() {
    >&2 echo 'usage: fg [OPTIONS] [init_query]

    OPTIONS:
        -m + --modified
        -d + --deleted
        -s + --stage
        -k + --killed
        -o + --others
        -i + --ignored
    '
    exit
}

fzf_search() {
    if ! cd "$(git rev-parse --show-toplevel)" &> /dev/null; then
        echo "git not exists"
        exit 1
    fi
    [[ $# -gt 0 ]] && filter_query="${*}"

    action=/tmp/$$
    [[ -e $action ]] && exit 1
    trap "command rm -f $action" EXIT SIGINT SIGTERM

    action_e="execute(${EDITOR} {+} > /dev/tty < /dev/tty)"

    readarray -t files < <(
        $git_prefix | lscolors | ${fzf_bin:-fzf} \
            --prompt="Gitfiles> " ${filter_query:+--filter "${filter_query}"} \
            --scheme path --exact --tiebreak "end,chunk,index" \
            --exit-0 --header-first \
            --header "keybindings: C-s(hsp), C-v(vsp), C-o(fzf-tmux-menu), A-e(execute editor), Enter(select or new file)" \
            --bind="ctrl-s:transform:echo h > $action; echo accept" \
            --bind="ctrl-v:transform:echo v > $action; echo accept" \
            --bind="ctrl-o:transform:echo m > $action; echo accept" \
            --bind="alt-e:transform:[[ \"${fzf_bin}\" ]] && echo \"ignore\" || echo \"${action_e}\"" \
            --bind="enter:accept-or-print-query" | sed -n "${filter_query:+1}p"
    )

}

exec_action() {
    flag=$(command cat "$action" 2> /dev/null)

    mkdir -p "$(dirname "${files}")" &> /dev/null
    if [[ "${flag}" =~ ^(h|v)$ ]]; then
        tmux splitw "-b${flag}" zsh -c "${EDITOR} ${files[*]}"
    elif [[ "${flag}" == m ]]; then
        set -x
        $CUSTOM_HOME/scripts/tmux/tmux-menu $(realpath "${files[@]}")
    else
        ${EDITOR} "${files[@]}"

    fi
}

main() {
    [[ $# -gt 1 && "$1" == help ]] && help
    [[ -v TMUX && $(command -v fzf-tmux) ]] && fzf_bin="fzf-tmux $FZF_TMUX_OPTS"

    # 判断是否是一个git目录
    if ! git rev-parse --is-inside-work-tree &> /dev/null; then
        echo "this is not a git directory"
        exit 1
    fi
    # global
    typeset files action git_prefix

    # args
    typeset -a git_flags
    typeset args

    args=$(getopt -o mdskio -l no-popup -n "$0" -- "$@")
    if [[ "$?" -ne 0 ]]; then
        echo "getopt parse error, args:${*}"
        exit 1
    fi
    eval set -- "$args"

    while true; do
        case $1 in
        --no-popup)
            fzf_bin=
            shift
            ;;
        -m)
            git_flags+=("--modified")
            shift
            ;;
        -d)
            git_flags+=("--deleted")
            shift
            ;;
        -s)
            git_flags+=("--stage")
            shift
            ;;
        -k)
            git_flags+=("--killed")
            shift
            ;;
        -i)
            git_flags+=("--ignored")
            shift
            ;;
        -o)
            git_flags+=("--others")
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "flag error"
            exit 1
            ;;

        esac
    done

    [[ $# -gt 0 && ${fzf_bin} ]] && fzf_bin=

    git_prefix="git ls-files --with-tree=HEAD ${git_flags[*]}"

    # 得到files
    fzf_search "$@"

    [[ ${#files[@]} -gt 0 ]] && exec_action
}

main "$@"
