#!/usr/bin/env zsh

# Desc: fzf tmux fifo with neovim block

emulate -L zsh
local fifo args direction

# 提前获取传入的标志
[[ $# > 0 && $1 =~ '^-[bfhv]{1,3}$' ]] && { direction=$1; shift } || direction="-bf"

# 确保一个tmux窗口只能同时存在一个各方向的分割
fifo=/tmp/nvim-tmux-exit-${direction#-}-$(tmux display-message -p "#S:#I")
mkfifo -m o+w $fifo || return 1

trap "command rm -f $fifo" EXIT SIGINT SIGTERM

(( $# == 0 )) && args="" || args="${(z)@}"


# 管道阻塞当前进程
tmux split-window $direction zsh -c "nvim $args; echo $? > $fifo" || return 1
exit <$fifo

# This needs fixed
# exec {fd}<$fifo
# exec {NVIM_FIFO}>&-
