#!/bin/env bash

toml_path="${CUSTOM_HOME}/scripts/tools/bin/toml"
config_dir="${CUSTOM_MARKS_FILE:-${XDG_CONFIG_HOME:-${HOME}/.config}/custom}"

toml::pmarks() {
    $toml_path -f "$config_dir/directories.toml" -t "marks" "pmarks"
}
toml::gmark() {
    $toml_path -f "$config_dir/directories.toml" -t "marks" "gmark" "$@"
}
